[package]
name = "cargo-optimize"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Automatically optimize Rust build times with zero configuration"
readme = "README.md"
repository = "https://github.com/yourusername/cargo-optimize"
keywords = ["cargo", "build", "optimization", "performance", "automation"]
categories = ["development-tools::build-utils", "development-tools::cargo-plugins"]

[lib]
name = "cargo_optimize"
path = "src/lib.rs"

[[bin]]
name = "cargo-optimize"
path = "src/bin/cargo-optimize.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
which = "6.0"
num_cpus = "1.16"
sysinfo = "0.32"
anyhow = "1.0"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5", features = ["derive"] }
dirs = "5.0"
walkdir = "2.5"
once_cell = "1.20"
regex = "1.11"
cargo_metadata = "0.19"
fs_extra = "1.3"
indicatif = "0.17"
colored = "2.1"

[dev-dependencies]
tempfile = "3.14"
criterion = "0.5"
pretty_assertions = "1.4"
proptest = "1.5"
arbitrary = { version = "1.3", features = ["derive"] }
fastrand = "2.1"
serde_json = "1.0"
rand = "0.8"

[build-dependencies]
# Build dependencies can be added here if needed

[features]
default = []
# The self-optimize feature has been removed to avoid cyclic dependencies

[profile.dev]
# Development profile - prioritize fast compilation
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.test]
# Test profile - balance speed and debugging
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 256

[profile.release]
# Release profile - prioritize runtime performance
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = 'abort'
incremental = false
codegen-units = 1
strip = true
