name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build API docs
      run: |
        cargo doc --no-deps --all-features
        echo '<meta http-equiv="refresh" content="0; url=cargo_optimize/index.html">' > target/doc/index.html
    
    - name: Generate README badges
      run: |
        cat > badges.md <<'END'
        ![CI](https://github.com/${{ github.repository }}/workflows/CI/badge.svg)
        ![Coverage](https://codecov.io/gh/${{ github.repository }}/branch/main/graph/badge.svg)
        ![Crates.io](https://img.shields.io/crates/v/cargo-optimize.svg)
        ![License](https://img.shields.io/crates/l/cargo-optimize.svg)
        ![Downloads](https://img.shields.io/crates/d/cargo-optimize.svg)
        END
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        force_orphan: true

  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate changelog
      uses: orhun/git-cliff-action@v2
      with:
        config: .github/cliff.toml
        args: --verbose
      env:
        OUTPUT: CHANGELOG.md
    
    - name: Commit changelog
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md
        git commit -m "docs: update changelog [skip ci]" || true
        git push
